### ISSUE TITLE
Question about utf support

### ISSUE THREAD

**Issue by andy5995** [cade-vs/vslib#7]
Hey @cade-vs Happy New year :)

What do you you think about this patch on the vfu-utf package in the AUR?

https://aur.archlinux.org/cgit/aur.git/tree/vfu-4.15-unicode.patch?h=vfu-utf

**Comment by cade-vs** [comment]
hi Andy and happy new year to you too!

setlocal() place is not in the library code, but vfu.cpp already calls setlocale() right in the start of main().
